Fix error parsing license if info is missing from libretro-super
Error was:

    File "templates/summary/wiki.txt.j2", line 18, in top-level template code
      | License= {{ '{{' }}{{ license_status }}|{{ addon.libretro_info.license.split('|') | join(', ') | default('?') }}{{ '}}' }}
  jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'license'